# Generated by Django 5.0.4 on 2024-04-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Polls", "0002_alter_player_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
